# Generated by Django 5.0.5 on 2026-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='fuel_type',
            field=models.CharField(default='Diesel', max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='station_name',
            field=models.CharField(max_length=255),
        ),
    ]
